name: crop_clasifier
description: "Flutter app for plant and crop identification"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.1
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  image_picker: ^1.1.2
  flutter_markdown: ^0.7.3
  flutter_smart_dialog: ^4.9.7+9
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  cached_network_image: ^3.4.0
  modal_bottom_sheet: ^3.0.0
  carousel_slider: ^4.2.1
  http: ^1.2.2
  shared_preferences: ^2.3.1
  firebase_auth: ^4.16.0
  image_cropper: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/slides/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  image_web: assets/images/splash.png
  android: true
  ios: true
  web: true
  android_12:
  #dart run flutter_native_splash:create
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/icon_dark.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon_dark.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  #    flutter pub run flutter_launcher_icons